# !name=AlightMotion
# !desc=AlightMotion

[Script]
AlightMotion = type=http-response,pattern=^https:\/\/us-central1-alight-creative\.cloudfunctions\.net\/getAccountStatusAndLicenses,requires-body=true,max-size=131072,timeout=10,script-path=https://raw.githubusercontent.com/Mikenco7878/ConfigShadowrocket/main/scripts/AlightMotion.js

[MITM]
hostname = %APPEND%, us-central1-alight-creative.cloudfunctions.net