# !name=BeautyPlus
# !desc=BeautyPlus

[Script]
BeautyPlus = type=http-response,pattern=https:\/\/(api\.mr\.pixocial\.com\/v1\/manual_unlock|newbeee-api\.beautyplus\.com\/api\/v1\/asset\/balance),requires-body=true,max-size=-1,timeout=60,script-path=https://raw.githubusercontent.com/Mikenco7878/ConfigShadowrocket/main/scripts/BeautyPlus.js

[MITM]
hostname = %APPEND%, api.mr.pixocial.com, newbeee-api.beautyplus.com