# !name=VSCO
# !desc=vsco

[Script]
VSCO = type=http-request,pattern=^https?:\/\/api\.revenuecat\.com\/v\d\/subscribers\/,script-path=https://raw.githubusercontent.com/Mikenco7878/ConfigShadowrocket/main/scripts/vsco.js
VSCO1 = type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v\d\/subscribers\/,requires-body=1,script-path=https://raw.githubusercontent.com/Mikenco7878/ConfigShadowrocket/main/scripts/vsco.js

[MITM]
hostname = %APPEND% api.revenuecat.com